package com.myfirstproject;
import com.myfirstproject.utilities.TestBase;
import org.junit.Assert;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
public class Day06_Iframe extends TestBase {
    @Test
    public void iframeTest() throws InterruptedException {
//    Go to https://the-internet.herokuapp.com/iframe
        driver.get("https://the-internet.herokuapp.com/iframe");
//    Verify the Bolded text contains “Editor”
        String boldedText = driver.findElement(By.xpath("//h3")).getText();
        Assert.assertTrue(boldedText.contains("Editor"));
//    Locate the text box
//        textBox is INSIDE an iframe. So i have to switch to that iframe
//        3 ways to handle frames : 1. index 2. id,name 3. webelement

//        1. INDEX: starts at 0
//        driver.switchTo().frame(0);

//         2. ID or NAME
//        driver.switchTo().frame("mce_0_ifr");

//        3. WEBELEMENT
        WebElement iFrame = driver.findElement(By.xpath("//iframe[@id='mce_0_ifr']"));
        driver.switchTo().frame(iFrame);
        WebElement textBox = driver.findElement(By.xpath("//p"));
//    Delete the text in the text box
//        driver.findElement(By.xpath("//p")).clear();
        textBox.clear();//clear deleted the text from an input
        Thread.sleep(5000);
//    Type “This text box is inside the iframe”
        textBox.sendKeys("This text box is inside the iframe");
        Thread.sleep(5000);
//    Verify the text Elemental Selenium text is displayed on the page
        driver.switchTo().parentFrame();//get 1 upper level using parentFrame
        driver.switchTo().defaultContent();//gets all the way to the root level
        WebElement elementalSelenium = driver.findElement(By.linkText("Elemental Selenium"));
        Assert.assertTrue(elementalSelenium.isDisplayed());
    }
}


/*
Interview:
How do you find the number of iframe on a page?
Sample Answer: iframes are created using iframe tag.
 I can use findElements by tag name that will return all of the element
  with iframe tags as List. Then I use size method to find the number of iframe in the list
Alternatively, I can also use findElements with xpath like
driver.findElements(By.xpath(//iframe)).size()
Can you five me the exact syntax?
Sure.
driver.findElements(By.tagName(“iframe”)).size();
Collapse




    /*
    * ***** What is alert?
    * Alerts are pop-ups generated by JS => Java scrits
    *
    * *****How do you handle Alerts?
    * Firstly I should switch the alerts then I can use accept, dismiss, getText, sendKeys
    * accept() => OK
    * dismiss() => Cancel
    * getText() => Returns text
    * sendKeys() => Types
    *
    * driver.switchTo().alert().getText();
    * driver.switchTo().alert().sendKeys();
    *
    * NOTE: If there is an alert on the page firstly we should handle
    * Without handling alert we can not continue on that page
    *
    *
    *
    * *****What is iFrame?
    * iFrame is used to add pages, maps, youtubes videos
    * iFrame generates html within the html
    * They can be accessed by using switchTo()
    *
    *
    * ****** How do you handle iFrames?
    * Firstly we should switch to iframe then we do automation
    * If the driver is not in the right frame, test case fails
    *
    * ***** How many way are there to switch to an iFrame?
    * There are 3 ways to switch to iframe => index, id/name, WebElement
    * *********************************************************************
    *  driver.switchTo().parentFrame(); //get 1 upper level by using parentFrame()
        driver.switchTo().defaultContent();//get us to default level
        *
        * ******How do you understand if an iframe on the page or not?
        * driver.findElement(By.xpath("//iframe")))
        * driver.findElements(By.xpath("//iframe")))
    *
    *
    *
    *
    *
    *
    *
    *
    *
    *
    *
    *
    * */





























































